import images from '../../assets/img/img-index'

const {
  img: {
    items: {
      absorbBulb,
      aspearBerry,
      balmMushroom,
      bigMushroom,
      bigPearl,
      blackSludge,
      charcoalPng,
      chestoBerry,
      chilanBerry,
      cometShard,
      dragonFang,
      dragonScale,
      electirizer,
      everstonePng,
      focusBand,
      gripClaw,
      hardStone,
      kingsRock,
      laggingTail,
      leftoversPng,
      leppaBerry,
      lightBall,
      luckyEgg,
      luckyPunch,
      lumBerry,
      magmarizerPng,
      magnetPng,
      metalCoat,
      metalPowder,
      moonStone,
      mysticWater,
      neverMeltIce,
      nuggetPng,
      oranBerry,
      ovalStone,
      payapaBerry,
      pearlPng,
      poisonBarb,
      psychicSeed,
      quickClaw,
      quickPowder,
      rawstBerry,
      sharpBeak,
      shedShell,
      shucaBerry,
      silverPowder,
      sitrusBerry,
      smokeBall,
      softSand,
      spellTag,
      stardustPng,
      starPiece,
      stick,
      thickClub,
      tinyMushroom,
      toxicOrb,
      twistedSpoon,
    },
  },
} = images

export const ImageObject = {
  'absorb-bulb': absorbBulb,
  'oran-berry': oranBerry,
  'sitrus-berry': sitrusBerry,
  'chilan-berry': chilanBerry,
  'light-ball': lightBall,
  'quick-claw': quickClaw,
  'grip-claw': gripClaw,
  'soft-sand': softSand,
  'moon-stone': moonStone,
  'leppa-berry': leppaBerry,
  'comet-shard': cometShard,
  'spell-tag': spellTag,
  'psychic-seed': psychicSeed,
  'lum-berry': lumBerry,
  'rawst-berry': rawstBerry,
  'charcoal': charcoalPng,
  'thick-club': thickClub,
  'smoke-ball': smokeBall,
  'mystic-water': mysticWater,
  'tiny-mushroom': tinyMushroom,
  'big-mushroom': bigMushroom,
  'balm-mushroom': balmMushroom,
  'electirizer': electirizer,
  'focus-band': focusBand,
  'silver-powder': silverPowder,
  'shed-shell': shedShell,
  'nugget': nuggetPng,
  'everstone': everstonePng,
  'hard-stone': hardStone,
  'kings-rock': kingsRock,
  'lagging-tail': laggingTail,
  'sharp-beak': sharpBeak,
  'payapa-berry': payapaBerry,
  'metal-coat': metalCoat,
  'magnet': magnetPng,
  'aspear-berry': aspearBerry,
  'never-melt-ice': neverMeltIce,
  'black-sludge': blackSludge,
  'toxic-orb': toxicOrb,
  'pearl': pearlPng,
  'poison-barb': poisonBarb,
  'big-pearl': bigPearl,
  'oval-stone': ovalStone,
  'lucky-egg': luckyEgg,
  'shuca-berry': shucaBerry,
  'stick': stick,
  'lucky-punch': luckyPunch,
  'stardust': stardustPng,
  'star-piece': starPiece,
  'magmarizer': magmarizerPng,
  'metal-powder': metalPowder,
  'quick-powder': quickPowder,
  'chesto-berry': chestoBerry,
  'leftovers': leftoversPng,
  'dragon-scale': dragonScale,
  'twisted-spoon': twistedSpoon,
  'dragon-fang': dragonFang,
}

export default ImageObject
