export const SET_DATA = 'SET_DATA'
export const SET_URLS = 'SET_URLS'
export const SET_POKEMON_DATA = 'SET_POKEMON_DATA'
export const SET_ABILITIES_DATA = 'SET_ABILITIES_DATA'

export default { SET_DATA, SET_URLS, SET_POKEMON_DATA, SET_ABILITIES_DATA }
