export const items = {
  'oran-berry': 4,
  'sitrus-berry': 1,
  'chilan-berry': 1,
  'light-ball': 1,
  'quick-claw': 3,
  'grip-claw': 2,
  'soft-sand': 1,
  'moon-stone': 4,
  'leppa-berry': 2,
  'comet-shard': 2,
  'rawst-berry': 3,
  'charcoal': 2,
  'tiny-mushroom': 2,
  'big-mushroom': 2,
  'balm-mushroom': 2,
  'silver-powder': 1,
  'shed-shell': 1,
  'nugget': 3,
  'everstone': 2,
  'hard-stone': 2,
  'kings-rock': 1,
  'lagging-tail': 1,
  'metal-coat': 1,
  'magnet': 1,
  'aspear-berry': 1,
  'never-melt-ice': 1,
  'black-sludge': 2,
  'toxic-orb': 1,
  'pearl': 2,
  'big-pearl': 2,
  'oval-stone': 1,
  'lucky-egg': 1,
  'lucky-punch': 1,
  'stardust': 2,
  'star-piece': 2,
  'magmarizer': 1,
  'metal-powder': 1,
  'quick-powder': 1,
  'chesto-berry': 1,
  'leftovers': 1,
  'dragon-scale': 2,
  'dragon-fang': 2,
}

export default items
